name: Build wheel

on:
  release:
    types:
      - created
  workflow_call:
    inputs:
      branch:
        default: main
        required: true
        type: string
  workflow_dispatch:
    inputs:
      branch:
        default: develop
        required: true
        type: choice
        options:
          - develop
          - main

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build_wheel:
    name: Build wheel
    runs-on: ubuntu-latest
    env:
      UV_NO_PROGRESS: true
    steps:

      - uses: actions/checkout@v7
        with:
          persist-credentials: false
          ref: ${{ inputs.branch }}
          repository: marcelotduarte/cx_Freeze

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          activate-environment: true
          cache-dependency-glob: "pyproject.toml"
          enable-cache: true
          python-version: "3.14"

      - name: Build sdist and wheels ${{ github.event_name }}
        run: ./ci/build-wheel.sh

      - name: Upload the artifact
        uses: actions/upload-artifact@v7
        with:
          name: cx-freeze-wheel
          path: wheelhouse
          compression-level: 0  # no compression
