name: Build packages

on:
  workflow_call:
    inputs:
      build_cx_logging:
        default: true
        required: false
        type: boolean
      build_lief:
        default: false
        required: false
        type: boolean
      build_freeze_core:
        default: false
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      build_cx_logging:
        default: false
        required: false
        type: boolean
      build_lief:
        default: false
        required: false
        type: boolean
      build_freeze_core:
        default: false
        required: false
        type: boolean

jobs:

  build_freeze_core:
    name: Build wheels for freeze-core
    if: ${{ inputs.build_freeze_core }}
    uses: marcelotduarte/freeze-core/.github/workflows/build.yml@main

  build_wheel:
    name: Build wheel for cx_Freeze
    uses: ./.github/workflows/build-wheel.yml
    with:
      branch: develop

  build_conda:
    name: Build conda packages for freeze-core and cx_freeze
    uses: ./.github/workflows/build-packages-conda.yml
    with:
      branch: develop
      #build_freeze_core: ${{ inputs.build_freeze_core }}

  build_msys2:
    name: Build msys2 packages
    uses: ./.github/workflows/build-packages-msys2.yml
    with:
      branch: develop

  build_wheel_cx_logging:
    name: Build cx_Logging
    if: ${{ inputs.build_cx_logging }}
    uses: ./.github/workflows/build-wheel-cxl.yml

  build_wheel_lief:
    name: Build LIEF
    if: ${{ inputs.build_lief }}
    uses: ./.github/workflows/build-wheel-lief.yml

  build_conda_index:
    needs: [build_conda]
    name: Conda index
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest

    steps:
      - uses: conda-incubator/setup-miniconda@v4
        with:
          activate-environment: freeze-index
          python-version: "3.14"
          channels: conda-forge

      - name: Download freeze-core conda artifacts
        uses: actions/download-artifact@v8
        with:
          path: build_artifacts
          pattern: freeze-core-conda-*
          merge-multiple: true

      - name: Download cx-freeze conda artifacts
        uses: actions/download-artifact@v8
        with:
          path: build_artifacts
          name: cx-freeze-conda

      - name: List of artifacts
        run: find build_artifacts -name '*'

      - name: Install conda index
        run: conda install conda-index

      - name: Run conda index
        run: |
          python -m conda_index --verbose -n packages/conda \
            --subdir noarch \
            --subdir linux-64 \
            --subdir osx-64 --subdir osx-arm64 \
            --subdir win-64 \
            build_artifacts

      - name: List of artifacts with index
        run: find build_artifacts -name '*'

      - name: Upload repository data to the conda artifact
        uses: actions/upload-artifact@v7
        with:
          name: cx-freeze-conda
          path: ./build_artifacts/*/*

  packages:
    name: Update packages repository
    needs:
      - build_conda_index
      # to wait for all artifacts
      - build_msys2
      - build_wheel
      #- build_freeze_core
      #- build_wheel_cx_logging
      #- build_wheel_lief
    env:
      LIEF_LINK: https://lief.s3-website.fr-par.scw.cloud/latest
      PACKAGES: https://marcelotduarte.github.io/packages
    permissions:
      actions: read
      contents: write
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v7
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: gh-pages
          repository: marcelotduarte/packages

      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Preserve make_index script
        run: |
          git checkout main
          cp make_index.py create_index.py
          git checkout gh-pages

      - name: Remove old wheels
        run: |
          git rm -f cx-freeze/* --ignore-unmatch
          git rm -f cx-logging/* --ignore-unmatch
          git rm -f freeze-core/* --ignore-unmatch
          git rm -f conda/* -r --ignore-unmatch
          git rm -f msys2/* --ignore-unmatch

      - name: Download all lief artifacts
        if: ${{ inputs.build_lief }}
        uses: actions/download-artifact@v8
        with:
          path: lief-wheels
          pattern: lief-*
          merge-multiple: true

      - name: Create index for LIEF
        run: |
          mkdir -p lief
          pushd lief
          for f in $(
            curl $LIEF_LINK/lief/ | grep -Eo "href=\"(.*win.*)\"" | cut -c"7-" | cut -d \" -f 1
          ); do
            touch `basename $f`
          done
          rm -rf lief/*-cp39-*.whl
          rm -rf lief/*-cp310-*.whl
          popd
          # redirected files
          python create_index.py lief --base LIEF
          sed -i 's,${{ env.PACKAGES }},${{ env.LIEF_LINK }},g' lief/index.md
          sed -i '/## /d' lief/index.md
          rm -rf lief/*.whl
          # local build
          if ${{ inputs.build_lief }}; then
            mv lief/index.md lief/dev.md
            mv lief-wheels/*.whl lief/ || true
            python create_index.py lief --base LIEF --mask "*.whl"
            mv lief/index.md lief/local.md
            # join
            echo -e "`cat lief/local.md`\n`cat lief/dev.md`\n">lief/index.md
            rm lief/local.md lief/dev.md
          fi

      - name: Download all cx-logging artifacts
        if: ${{ inputs.build_cx_logging }}
        uses: actions/download-artifact@v8
        with:
          path: cx-logging
          pattern: cx-logging-*
          merge-multiple: true

      - name: Create index for cx-logging wheels
        if: ${{ inputs.build_cx_logging }}
        run: python create_index.py cx-logging --base cx_Logging

      - name: Download all freeze-core artifacts
        if: ${{ inputs.build_freeze_core }}
        uses: actions/download-artifact@v8
        with:
          path: freeze-core
          pattern: freeze-core-*
          merge-multiple: true

      - name: Create index for freeze-core wheels
        if: ${{ inputs.build_freeze_core }}
        run: python create_index.py freeze-core

      - name: Download all cx_Freeze artifacts
        uses: actions/download-artifact@v8
        with:
          path: cx-freeze
          pattern: cx-freeze-wheel

      - name: Create index for cx_Freeze wheels
        run: python create_index.py cx-freeze --base cx_Freeze

      - name: Download all msys2 artifacts
        uses: actions/download-artifact@v8
        with:
          path: msys2
          pattern: cx-freeze-msys2-*
          merge-multiple: true

      - name: Create index for python-cx-freeze and python-freeze-core (msys2)
        run: >
          python create_index.py msys2
          --base "msys2 packages (python-cx-freeze and python-freeze-core)"
          --mask "*.tar.zst"

      - name: Download cx-freeze conda artifacts
        uses: actions/download-artifact@v8
        with:
          path: conda
          name: cx-freeze-conda

      - name: Download freeze-core conda artifacts
        uses: actions/download-artifact@v8
        with:
          path: conda
          pattern: freeze-core-conda-*
          merge-multiple: true

      - name: Create index for cx_freeze and freeze-core (conda)
        run: >
          python create_index.py conda
          --base "conda-forge (cx_freeze and freeze-core)"
          --mask "cx_freeze*.conda" --mask "cx_freeze*.tar.bz2"
          --mask "freeze-core*.conda" --mask "freeze-core*.tar.bz2"

      - name: Cleanup
        run: rm -rf lief-wheels *.py *.md PKGBUILD*

      - name: Create packages template
        run: |
          # configuration
          echo "theme: jekyll-theme-architect">_config.yml

          # template
          VERSION=$(ls cx-freeze | (read name; echo $name) | sed 's/-/ /g' | awk '{print $2}')
          echo -e "# Development packages for cx_Freeze\n">index.md
          echo -e "## Version $VERSION\n">>index.md
          echo -e "Development wheels for [cx_Freeze](cx-freeze/index.md).\n">>index.md
          if ${{ inputs.build_freeze_core }}; then
            echo -e "Development wheels for [freeze-core](freeze-core/index.md).\n">>index.md
          fi
          echo -e "Development packages for MSYS2 [python-cx-freeze](msys2/index.md).\n">>index.md
          echo -e "Development packages for conda-forge [cx_freeze](conda/index.md).\n">>index.md
          if ${{ inputs.build_cx_logging }}; then
            echo -e "# Packages for cx_Logging 3.2.2 \[Windows\]\[Python 3.13+\]\n">>index.md
            echo -e "Unofficial wheels for [cx_Logging](cx-logging/index.md).\n">>index.md
          fi
          echo -e "# Packages for LIEF \[Windows\]\n">>index.md
          echo -e "## For Python 3.11-3.15\n">>index.md
          echo -e "Development wheels for [LIEF](lief/index.md).\n">>index.md

      - name: Publish cx_Freeze packages
        run: |
          git config user.name "Marcelo Duarte"
          git config user.email "12752334+marcelotduarte@users.noreply.github.com"
          git add .
          git commit -m "Publish cx_Freeze packages"
          git push --set-upstream origin gh-pages
